version: '3' 
networks:
 default:
    external:
      name: my_network
  
services: 
  nginx:  
    image: nginx:stable-alpine  
    container_name: nginx 
    ports:  
      - 8088:80
    volumes:  
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php
      - mysql

  mysql:  
    image: mysql:5.7.22
    container_name: mysql
    tty: true
    ports:
      - 4306:3306
    volumes :
      - ./mysql:/var/lib/mysql 
    environment:
        MYSQL_DATABASE: "bassant"
        MYSQL_USER: "bassant"
        MYSQL_PASSWORD: "secret"
        MYSQL_ROOT_PASSWORD: "secret"
        SERVICES_TAGES: dev
        SERVICE_NAME: mysql                                                                                            
           
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"